version: "3.8"

services:
  dev-front:
    container_name: softprocess_front
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
  dev-backend:
    container_name: softprocess_back
    image: gcpasquadproduto/softplan-desafio-frontend
    ports:
      - "3002:3002"
